name: Backend Tests & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: --name=mongo_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js with nvm
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install Dependencies
        run: npm ci

      - name: Wait for MongoDB to be Ready
        run: npx wait-on tcp:localhost:27017 -t 60000 # Wait up to 60 seconds

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test

      - name: Cleanup MongoDB
        if: always()
        run: docker stop mongo_test || true

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Notify deployment success
        run: |
          echo "🚀 Deployment Successful! 🔗 Access the backend at: ${{ secrets.RENDER_URL }}"


